name: Build IPA Only (Manual URL)

on:
  workflow_dispatch:
    inputs:
      LINK_IPA:
        description: 'Direct download link to decrypted Spotify IPA'
        required: true
        type: string

env:
  SWIFTPROTOBUF_VERSION: "1.29.0"

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Install deps
        run: |
          brew install make dpkg ldid jq
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Copy SwiftProtobuf
        run: |
          mkdir swiftprotobuf && cd "$_"
          wget https://github.com/whoeevee/swift-protobuf/releases/download/${{ env.SWIFTPROTOBUF_VERSION }}/org.swift.protobuf.swiftprotobuf_${{ env.SWIFTPROTOBUF_VERSION }}_iphoneos-arm.deb
          ar -x org.swift.protobuf.swiftprotobuf_${{ env.SWIFTPROTOBUF_VERSION }}_iphoneos-arm.deb
          tar -xvf data.tar.lzma
          cp -r Library/Frameworks/SwiftProtobuf.framework $THEOS/lib

      - name: Build tweak
        run: |
          make package FINALPACKAGE=1
          echo "filename=$(find ./packages -name '*.deb' -not -name '*debug*' | head -n1)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: tweak
          path: ${{ env.filename }}

  patchipa:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Download Spotify IPA from given link
        run: |
          curl -L "${{ github.event.inputs.LINK_IPA }}" -o spotify.ipa

      - name: Setup tools
        run: |
          git clone https://github.com/whoeevee/ivinject.git
          cp -r ivinject/KnownFrameworks ~/.ivinject
          wget https://github.com/whoeevee/ivinject/releases/download/first/ivinject-arm64
          sudo mv ivinject-arm64 /usr/local/bin/ && sudo chmod +x /usr/local/bin/ivinject-arm64
          wget https://github.com/asdfzxcvbn/ipapatch/releases/download/v2.1.0/ipapatch.macos-arm64
          sudo mv ipapatch.macos-arm64 /usr/local/bin/ipapatch && sudo chmod +x /usr/local/bin/ipapatch

      - name: Patch IPA
        run: |
          ROOTFUL=$(find . -name '*iphoneos-arm.deb' | head -n1)
          ivinject-arm64 spotify.ipa patched.ipa -i "$ROOTFUL"
          ipapatch -input patched.ipa -output spotify-binathr-patched.ipa

      - uses: actions/upload-artifact@v4
        with:
          name: patched-ipa
          path: spotify-binathr-patched.ipa
